#
# Copyright (c) 2020-22 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: CI (pushes and pull requests)
on:
  pull_request:
    branches-ignore:
      - 'devspaces-3*rhel-8'
  push:
    branches:
      - 'devspaces-3*rhel-8'
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:

    - name: Login to quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        # for pushing to quay.io/devspaces/
        username: ${{ secrets.DS_QUAY_USERNAME }}
        password: ${{ secrets.DS_QUAY_PASSWORD }}
    - uses: actions/checkout@v2
      name: Fetch Dev Spaces Theia source code
    - uses: actions/setup-node@v1
      name: Set nodejs version = 12.x
      with:
        node-version: '12.x'
    - name: build
      run: |
        docker image prune -a -f
        FLAGS="--gh"
        if [[ ${{ github.event_name }} == "pull_request" ]]; then # pull request
          FLAGS="--pr"
        fi
        git config --global user.name "Red Hat Release Bot"
        git config --global user.email "nickboldt+devstudio-release@gmail.com"
        cat BUILD_PARAMS
        echo "$(cat BUILD_COMMAND) ${FLAGS}"
        $(cat BUILD_COMMAND) ${FLAGS}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
